### ISSUE TITLE
Checksum missing darkcoin-0.11.1.25-win32-setup.exe

### ISSUE THREAD

**Issue by vertoe** [dashpay/dash-binaries#32]
https://github.com/darkcoinproject/darkcoin-binaries/blob/master/darkcoin-0.11.1.25-win32-setup.exe.DIGESTS.txt is empty.

**Comment by jonathancross** [comment]
Seems this is obsolete?

**Comment by UdjinM6** [comment]
tnx for reminding @jonathancross , closing this
